name: CI/CD

on: 
  push:
    branches:
      - master

env:
  CI: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        npm i
    # - run: |
    #     npm run test
    - run: |
        npm run build
    - name: Upload build
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: Build
        # Directory containing files to upload
        path: build

  deploy-staging:
    needs: [build]
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
    
    runs-on: ubuntu-latest
    steps:
      - name: Download build
        uses: actions/download-artifact@v1.0.0
        with:
          # Artifact name
          name: Build
          # Destination path
          path: build
  ### setup env-file from secrets
      - uses: TickX/var-to-dotenv@v1.1.1
        with:
          key: 'REACT_APP_BACKEND_API_KEY' # [Required]
          value: ${{secrets.STAGING_BACKEND_API_KEY}} # [Required]
      - uses: TickX/var-to-dotenv@v1.1.1
        with:
          key: 'REACT_APP_BACKEND_AUTH_DOMAIN' # [Required]
          value: ${{secrets.STAGING_BACKEND_PROJECT_ID}.firebaseapp.com} # [Required]
      - uses: TickX/var-to-dotenv@v1.1.1
        with:
          key: 'REACT_APP_BACKEND_DATABASE_URL' # [Required]
          value: ${https://{secrets.STAGING_BACKEND_PROJECT_ID}.firebaseio.com} # [Required]
      - uses: TickX/var-to-dotenv@v1.1.1
        with:
          key: 'REACT_APP_BACKEND_PROJECT_ID' # [Required]
          value: ${{secrets.STAGING_BACKEND_PROJECT_ID}} # [Required]
      - uses: TickX/var-to-dotenv@v1.1.1
        with:
          key: 'REACT_APP_BACKEND_STORAGE_BUCKET' # [Required]
          value: ${{secrets.STAGING_BACKEND_PROJECT_ID}.appspot.com} # [Required]
      - uses: TickX/var-to-dotenv@v1.1.1
        with:
          key: 'REACT_APP_BACKEND_MESSAGE_SENDER_ID' # [Required]
          value: ${{secrets.SOME_API_URI}} # [Required]
      - uses: TickX/var-to-dotenv@v1.1.1
        with:
          key: 'REACT_APP_BACKEND_SENDER_APP_ID' # [Required]
          value: ${{secrets.STAGING_BACKEND_SENDER_APP_ID}} # [Required]
      - uses: TickX/var-to-dotenv@v1.1.1
        with:
          key: 'REACT_APP_BACKEND_MEASUREMENT_ID' # [Required]
          value: ${{secrets.STAGING_BACKEND_MEASUREMENT_ID}} # [Required]
      
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v1.3.0
        with:
          repo: sharemycart/sharemycart
          target_branch: gh-pages
          build_dir: build
          fqdn: app.sharemycart.com