name: CI/CD

on:
  push:
    branches:
      - master
      - cicd
      - develop
  pull_request:
env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Initialize workflow variables
        id: vars
        shell: bash
        run: |
            SUBDOMAIN="staging"
            if [ "$BRANCH" == "refs/heads/master" ]; then 
            SUBDOMAIN="app"; 
            fi;
            echo ::set-output name=SUBDOMAIN::${SUBDOMAIN}
            echo ::set-output name=DOMAIN::${SUBDOMAIN}.sharemycart.com
            echo ::set-output name=PUBLIC_URL::https://${SUBDOMAIN}.sharemycart.com
        env:
          BRANCH: ${{ github.ref }}
      - name: print vars
        run: |
          echo "Branch: $BRANCH"
          echo "Public URL: $PUBLIC_URL"
        env:
          BRANCH: ${{ github.ref }}
          PUBLIC_URL: ${{ steps.vars.outputs.PUBLIC_URL }}
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: |
          npm i
      # - run: |
      #     npm run test
      - name: Setup env
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_REACT_APP_BASENAME: ${{ steps.vars.outputs.PUBLIC_URL }}
          envkey_REACT_APP_BACKEND_API_KEY: ${{secrets.STAGING_BACKEND_API_KEY}}
          envkey_REACT_APP_BACKEND_AUTH_DOMAIN: ${{secrets.STAGING_BACKEND_PROJECT_ID}}.firebaseapp.com
          envkey_REACT_APP_BACKEND_DATABASE_URL: https://${{secrets.STAGING_BACKEND_PROJECT_ID}}.firebaseio.com
          envkey_REACT_APP_BACKEND_PROJECT_ID: ${{secrets.STAGING_BACKEND_PROJECT_ID}}
          envkey_REACT_APP_BACKEND_STORAGE_BUCKET: ${{secrets.STAGING_BACKEND_PROJECT_ID}}.appspot.com
          envkey_REACT_APP_BACKEND_MESSAGE_SENDER_ID: ${{secrets.STAGING_BACKEND_MESSAGE_SENDER_ID}}
          envkey_REACT_APP_BACKEND_SENDER_APP_ID: ${{secrets.STAGING_BACKEND_SENDER_APP_ID}}
          envkey_REACT_APP_BACKEND_MEASUREMENT_ID: ${{secrets.STAGING_BACKEND_MEASUREMENT_ID}}
          envkey_REACT_APP_CONFIRMATION_EMAIL_REDIRECT: ${{ steps.vars.outputs.PUBLIC_URL }}
          file_name: .env.staging
      - run: |
          npm run build:staging
      - name: Upload build
        uses: actions/upload-artifact@v1.0.0
        with:
          # Artifact name
          name: Build
          # Directory containing files to upload
          path: build

  deploy:
    needs: [build]
    # if: github.ref == 'refs/heads/master' #TODO: Switch to real staging once we're out of Beta
    env:
      GITHUB_PAT: ${{ secrets.DEPLOYMENT_PAT }}
    runs-on: ubuntu-latest
    steps:
      - name: Download build
        uses: actions/download-artifact@v1.0.0
        with:
          # Artifact name
          name: Build
          # Destination path
          path: build
      - name: Initialize workflow variables
        id: vars
        shell: bash
        run: |
            SUBDOMAIN="staging"
            REPO="sharemycart/app-staging"
            if [ "$BRANCH" == "refs/heads/master" ]; then 
            SUBDOMAIN="app"; 
            REPO="sharemycart/sharemycart"; 
            fi;
            echo ::set-output name=SUBDOMAIN::${SUBDOMAIN}
            echo ::set-output name=DOMAIN::${SUBDOMAIN}.sharemycart.com
            echo ::set-output name=REPO::${REPO}
        env:
          BRANCH: ${{ github.ref }}
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v1.3.0
        with:
          repo: ${{ steps.vars.outputs.REPO }}
          target_branch: gh-pages
          build_dir: build
          fqdn: ${{ steps.vars.outputs.DOMAIN }}
